# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-kqIIZzYqQ0v1wFHj6kqwCB9l0dVlwlO
"""

import csv
import json
import os
from datetime import datetime

# Sample inbound leads to simulate incoming form submissions
INCOMING_LEADS = [
    {
        "name": "Sarah Jenkins",
        "email": "sarah@growthbrands.io",
        "message": "Looking to automate our daily inventory updates from Shopify to Airtable. Budget is $1,500, need it in 2 weeks."
    },
    {
        "name": "Alex Rivera",
        "email": "alex@freemail.com",
        "message": "Hey, do you do free consultations? Just wondering what tools exist for scraping."
    },
    {
        "name": "David Chen",
        "email": "dchen@logisticsflow.com",
        "message": "We need an end-to-end Python pipeline to parse 500 PDF invoices a week into QuickBooks. Budget is $4,000. Looking to start immediately."
    }
]

def qualify_lead(lead_dict: dict) -> dict:
    """
    Evaluates raw inbound message and assigns priority and category.
    (This logic can be rule-based or plugged into an LLM API).
    """
    msg = lead_dict["message"].lower()

    # Priority scoring logic
    if any(keyword in msg for keyword in ["immediately", "urgent", "2 weeks"]) or "$1" in msg or "$4" in msg:
        priority = "High"
    elif "free" in msg or "wondering" in msg:
        priority = "Low"
    else:
        priority = "Medium"

    lead_dict["priority"] = priority
    lead_dict["processed_at"] = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    # Generate quick automated response draft
    if priority == "High":
        lead_dict["draft_reply"] = (
            f"Hi {lead_dict['name']},\n\n"
            "Thanks for reaching out! Your timeline and scope look clear. "
            "I have immediate availability for this integration. Let's set up a quick 10-minute kickoff call.\n"
        )
    else:
        lead_dict["draft_reply"] = (
            f"Hi {lead_dict['name']},\n\n"
            "Thanks for your inquiry. To help me understand if this is a good fit, "
            "could you share a few more specifics regarding your project requirements?\n"
        )

    return lead_dict

def sync_to_crm(leads: list, filename="crm_leads.csv"):
    """
    Writes processed leads into a structured CSV ledger.
    """
    file_exists = os.path.exists(filename)
    fields = ["name", "email", "priority", "message", "processed_at", "draft_reply"]

    with open(filename, mode="w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fields)
        writer.writeheader()
        for lead in leads:
            writer.writerow(lead)

    print(f"[SUCCESS] Processed {len(leads)} leads and saved to {filename}")

# Run pipeline
if __name__ == "__main__":
    processed_leads = [qualify_lead(lead) for lead in INCOMING_LEADS]
    sync_to_crm(processed_leads)

import csv
import os
import requests
from datetime import datetime

# Paste your Discord webhook URL inside quotes, or leave as empty string "" to see simulation
DISCORD_WEBHOOK_URL = "https://discord.com/api/webhooks/1554188406211223583/wH8R6cGmx3qdDlEt1YyERBzXGFDR1oCbNrZnJVUvwNjnQhNLYxLyviyncKVp5ZpXZCrR"

INCOMING_LEADS = [
    {
        "name": "Sarah Jenkins",
        "email": "sarah@growthbrands.io",
        "message": "Looking to automate our daily inventory updates from Shopify to Airtable. Budget is $1,500, need it in 2 weeks."
    },
    {
        "name": "Alex Rivera",
        "email": "alex@freemail.com",
        "message": "Hey, do you do free consultations? Just wondering what tools exist for scraping."
    },
    {
        "name": "David Chen",
        "email": "dchen@logisticsflow.com",
        "message": "We need an end-to-end Python pipeline to parse 500 PDF invoices a week into QuickBooks. Budget is $4,000. Looking to start immediately."
    }
]

def qualify_lead(lead_dict: dict) -> dict:
    msg = lead_dict["message"].lower()

    if any(k in msg for k in ["immediately", "urgent", "2 weeks"]) or "$1" in msg or "$4" in msg:
        priority = "HIGH"
    elif "free" in msg or "wondering" in msg:
        priority = "LOW"
    else:
        priority = "MEDIUM"

    lead_dict["priority"] = priority
    lead_dict["processed_at"] = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    return lead_dict

def send_instant_alert(lead: dict, webhook_url: str):
    """
    Sends a formatted alert directly to team chat for high priority inquiries.
    """
    payload = {
        "content": "🚨 **HOT INBOUND LEAD DETECTED** 🚨",
        "embeds": [
            {
                "title": f"Lead: {lead['name']}",
                "color": 15158332,  # Red alert banner
                "fields": [
                    {"name": "Email", "value": lead["email"], "inline": True},
                    {"name": "Priority", "value": lead["priority"], "inline": True},
                    {"name": "Inquiry Details", "value": lead["message"], "inline": False},
                    {"name": "Received At", "value": lead["processed_at"], "inline": False}
                ],
                "footer": {"text": "Automated Lead Engine v1.0"}
            }
        ]
    }

    if webhook_url.strip():
        response = requests.post(webhook_url, json=payload)
        if response.status_code == 204:
            print(f"[ALERT SENT] Notification pushed to team chat for: {lead['name']}")
        else:
            print(f"[ALERT FAILED] Code {response.status_code}")
    else:
        # Simulated console alert
        print(f"[ALERT SIMULATED] Would ping team channel: '{lead['name']}' ({lead['priority']})")

def process_pipeline(leads: list, webhook_url: str):
    processed = []
    for raw in leads:
        lead = qualify_lead(raw)
        processed.append(lead)

        # Only notify team immediately if priority is HIGH
        if lead["priority"] == "HIGH":
            send_instant_alert(lead, webhook_url)

    # Save to CRM CSV
    filename = "crm_leads.csv"
    fields = ["name", "email", "priority", "message", "processed_at"]
    with open(filename, mode="w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fields)
        writer.writeheader()
        for l in processed:
            writer.writerow({k: l[k] for k in fields})

    print(f"\n[PIPELINE COMPLETE] Logged {len(processed)} leads to {filename}")

# Run it
process_pipeline(INCOMING_LEADS, DISCORD_WEBHOOK_URL)